title: 한국인터넷.한국 1부 종료 완전 이전 기록
description: 한글 도메인 한국인터넷.한국 1부 종료 이후 기록의 GitHub Pages 완전 이전 보관소
lang: ko-KR
timezone: Asia/Seoul
theme: minima

author:
  name: Korean Internet Admin

header_pages:
  - incident-notes/index.md

minima:
  skin: auto

plugins:
  - jekyll-feed